# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiAccountOauthDemo' do


  pod 'MultiAccountOauth', :path => '../'
  pod 'RandomColorSwift'

  use_frameworks!

  target 'MultiAccountOauthDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiAccountOauthDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
